//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EyeWebService.Models
{
    public partial class tblAddress
    {
        public int addressId { get; set; }
        public string addressType { get; set; }
        public string loginId { get; set; }
        public string streetName { get; set; }
        public string city { get; set; }
        public string stateName { get; set; }
        public string country { get; set; }
        public string zipcode { get; set; }
        public string phoneNo { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
