//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EyeWebService.Models
{
    public partial class tblGame
    {
        public int gameId { get; set; }
        public string gameName { get; set; }
        public string gameDescription { get; set; }
        public int therapyId { get; set; }
    
        public virtual tblTherapy tblTherapy { get; set; }
    }
}
