//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EyeWebService.Models
{
    public partial class tblParentXREF
    {
        public int parentId { get; set; }
        public int patientId { get; set; }
        public int providerId { get; set; }
    }
}
