//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace EyeWebService.Models
{
    public partial class tblTherapy
    {
        public tblTherapy()
        {
            this.tblGames = new HashSet<tblGame>();
        }
    
        public int therapyId { get; set; }
        public string therapyName { get; set; }
        public string therapyDescription { get; set; }
    
        public virtual ICollection<tblGame> tblGames { get; set; }
    }
}
