//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EyeWebService.Models
{
    public partial class tblUserType
    {
        public int userTypeId { get; set; }
        public string userType { get; set; }
    }
}
