//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace EyeWebService.Models
{
    public partial class tblUser
    {
        public int userId { get; set; }
        public string loginId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int userTypeId { get; set; }
        public Nullable<DateTime> dateOfBirth { get; set; }
        public string gender { get; set; }
    }
}
